version: "3.8"

services:
  edge:
    image: placeos/edge:latest
    container_name: edge
    environment:
      - PLACE_URI=https://placeos-dev.aca.im
      - PLACE_EDGE_KEY=8ba928b3465512ee47de48860c7ca902
